"""Normalized signal schema for all intel sources."""

from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


class SignalSource(str, Enum):
    """Originating intel source."""

    ONCHAIN = "onchain"
    SOCIAL = "social"
    NEWS = "news"
    TECHNICAL = "technical"
    PREDICTION_MARKET = "prediction_market"
    ARBITRAGE = "arbitrage"


class SignalType(str, Enum):
    """Classification of the trading signal."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    ALERT = "alert"
    ARBITRAGE = "arbitrage"
    SENTIMENT = "sentiment"
    WHALE_MOVE = "whale_move"
    LIQUIDITY_SHIFT = "liquidity_shift"


class Signal(BaseModel):
    """
    Common schema for every normalized signal.
    All fields are optional except id, source, type, and timestamp.
    """

    id: str = Field(..., description="UUID v4 generated by aggregator")
    source: SignalSource = Field(..., description="Intel source")
    type: SignalType = Field(..., description="Signal classification")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of signal creation",
    )
    symbol: Optional[str] = Field(
        default=None, description="Primary asset symbol, e.g. BTC, ETH, USDC"
    )
    quote_symbol: Optional[str] = Field(
        default=None, description="Quote asset, e.g. USD, USDC"
    )
    confidence: Optional[Decimal] = Field(
        default=None,
        ge=0,
        le=1,
        description="Confidence score 0.0–1.0",
    )
    direction: Optional[str] = Field(
        default=None, description="long / short / neutral"
    )
    price: Optional[Decimal] = Field(default=None, description="Relevant price point")
    volume_24h: Optional[Decimal] = Field(default=None)
    liquidity_usd: Optional[Decimal] = Field(default=None)
    sentiment_score: Optional[Decimal] = Field(
        default=None, ge=-1, le=1, description="-1 bearish to +1 bullish"
    )
    raw_payload: Dict[str, Any] = Field(
        default_factory=dict, description="Unmodified source payload"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Source-specific metadata (block number, tweet id, etc)",
    )
    tags: List[str] = Field(default_factory=list)

    @field_validator("confidence", "sentiment_score", mode="before")
    @classmethod
    def _coerce_decimal(cls, v: Any) -> Any:
        if v is None:
            return v
        return Decimal(str(v))

    @field_validator("price", "volume_24h", "liquidity_usd", mode="before")
    @classmethod
    def _coerce_price_decimal(cls, v: Any) -> Any:
        if v is None:
            return v
        return Decimal(str(v))

    def to_redis_message(self) -> str:
        """JSON string for Redis pub/sub."""
        return self.model_dump_json()

    @classmethod
    def from_raw(cls, source: SignalSource, raw: Dict[str, Any], **overrides) -> "Signal":
        """Factory for building a Signal from a raw dict."""
        data = {
            "source": source.value,
            "raw_payload": raw,
            **overrides,
        }
        return cls(**data)
